platform:
  - x86
  - x64

environment:
 matrix:
  - DC: dmd
    DVersion: 2.075.0
  - DC: dmd
    DVersion: 2.072.1
  - DC: ldc
    DVersion: 1.2.0
  - DC: ldc
    DVersion: 1.0.0

skip_tags: true

install:
  - ps: function SetUpDCompiler
        {
            if($env:DC -eq "dmd"){
              if($env:platform -eq "x86"){
                $env:DConf = "m32";
              }
              elseif($env:platform -eq "x64"){
                $env:DConf = "m64";
              }
              echo "downloading ...";
              $env:toolchain = "msvc";
              $version = $env:DVersion;
              Invoke-WebRequest "http://downloads.dlang.org/releases/2.x/$($version)/dmd.$($version).windows.7z" -OutFile "c:\dmd.7z";
              echo "finished.";
              pushd c:\\;
              7z x dmd.7z > $null;
              popd;
            }
            elseif($env:DC -eq "ldc"){
              echo "downloading ...";
              if($env:platform -eq "x86"){
                $env:DConf = "m32";
                $env:Model = "32";
              }
              elseif($env:platform -eq "x64"){
                $env:DConf = "m64";
                $env:Model = "64";
              }
              $env:toolchain = "msvc";
              $version = $env:DVersion;
              Invoke-WebRequest "https://code.dlang.org/files/dub-1.0.0-windows-x86.zip" -OutFile "c:\dub.zip";
              pushd c:\\;
              7z x dub.zip -odub > $null;
              popd;
              Invoke-WebRequest "https://github.com/ldc-developers/ldc/releases/download/v$($version)/ldc2-$($version)-win$($env:Model)-msvc.zip" -OutFile "c:\ldc.zip";
              echo "finished.";
              pushd c:\\;
              7z x ldc.zip > $null;
              popd;
            }
        }
  - ps: SetUpDCompiler

before_build:
  - ps: if($env:platform -eq "x86"){
            $env:compilersetupargs = "x86";
            $env:Darch = "x86";
            $env:Model = "32";
          }
        elseif($env:platform -eq "x64"){
            $env:compilersetupargs = "amd64";
            $env:Darch = "x86_64";
            $env:Model = "64";
        }
  - ps : if($env:DC -eq "dmd"){
           $env:PATH += ";C:\dmd2\windows\bin;";
         }
         elseif($env:DC -eq "ldc"){
           $version = $env:DVersion;
           echo "LS";
           ls;
           echo "ls ldc";
           ls "C:\ldc2-$($version)-win$($env:Dmodel)-msvc\bin";
           $env:PATH += ";C:\ldc2-$($version)-win$($env:Dmodel)-msvc\bin";
           $env:PATH += ";C:\dub";
           $env:DC = "ldc2";
         }
  - ps: $env:compilersetup = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall";
  - '"%compilersetup%" %compilersetupargs%'

build_script:
 - echo dummy build script - dont remove me

test_script:
 - echo %PLATFORM%
 - echo %Darch%
 - echo %DC%
 - echo %PATH%
 - '%DC% --version'
 - dub build -b debug -a %Darch% --compiler=%DC%
 - dub build -b release -a %Darch% --compiler=%DC%
